### ISSUE TITLE
Check for expired CA certificate

### ISSUE THREAD

**Issue by mhils** [mitmproxy/netlib#101]
The mitmproxy CA certificate is generated on the first start of mitmproxy. Due to mitmproxy/mitmproxy/issues/815, the certificate is only valid for three years. `CertStore.from_store` should check if the CA certificate is still valid and raise an error if that is not the case (which we can then act on in mitmproxy).

**Comment by tinius** [comment]
Seems to me that this would do it:

    ca = OpenSSL.crypto.load_certificate(
                OpenSSL.crypto.FILETYPE_PEM,
                raw)
    if ca.has_expired():
        raise CertExpiredException("mitmproxy's certificate has expired.")

That being said, is there a reason why we shouldn't just call create_store on the spot?

**Comment by mhils** [comment]
> That being said, is there a reason why we shouldn't just call create_store on the spot?

I'm not sure what's the best way, but silently replacing the CA (without user notification) is not really optimal. At the very least, we need some kind of notification that a new certificate has been generated.

**Comment by mhils** [comment]
This issue was moved to mitmproxy/mitmproxy#939
