### ISSUE TITLE
Add a classmethod to convert odict to dict

### ISSUE THREAD

**Issue by MatthewShao** [mitmproxy/netlib#106]
Lately I'm using libmproxy with requests to handle HTTP flow. 
I find that many method in ```libmproxy.protocol.http``` will return a ```netlib.odict.ODict``` object, but  built-in ```dict``` type is used more frequently when interacting with other packages, such as requests.
So, a classmethod that return the built-in ```dict``` type in ```netlib.odict.ODict``` will be very handy.

I would like to add this feature if you think it is a good idea!

**Comment by mhils** [comment]
The key problem here is that an ODict can have multiple entries with the same key - how would you transform that to a dict? For HTTP headers we have RFC7230, which allows us to concat with `,`, but that doesn't work for the other cases.
If you want to export to a "pure" datastructure, you'd have a `[ [key, value], ...]` list, i.e. `odict.lst`.

Thoughts?

**Comment by MatthewShao** [comment]
Firstly, sorry for my inconsiderable idea. I only focus on the ```get_form()``` and ```get_query()```method but never consider about the multiple entries with same key. You see, I' m working with requests, which send a POST request like:
```python
requests.post("http://httpbin.org/post", data = {"key":"value"})
```
It requires a dict type object as input , at the beginning I just simply use ```dict(ODict)``` to attain that. And it will return something like ```{"key1":['value1'], "key2":['value2']}```. Basically, I want a function can return the built-in dict type when I dealing with these things.
Maybe I make this question too general, but is it possible to add these function somewhere else?

**Comment by mhils** [comment]
> Basically, I want a function can return the built-in dict type when I dealing with these things.

Not sure if I understand you correctly. :smiley:
Given the following `ODict.lst` as input:
```python
[
  ["a", 42],
  ["a", 43],
  ["b", 44]
]
```

What does your function return?

**Comment by MatthewShao** [comment]
As I said before, I never consider about the multiple entries with same key. :pensive:
I know that parameters with same name are allowed in HTTP, but I surprisingly find that ```requests``` does not support this feature. It seems that there is no way to send correct requests with data like you said above with ```requests```. So I will try to use urllib2 to implement the HTTP request, I think use dict(ODict) will be OK. That is ```{"a":[42,43],"b":[44]}```. Thanks for your help , can close this issue now!

**Comment by mhils** [comment]
Ok, great. Thanks for the suggestion anyway! :smiley:
