### ISSUE TITLE
module 'socket' has no attribute '_fileobject' in python 3.5

### ISSUE THREAD

**Issue by AlexandreRoba** [mitmproxy/netlib#113]
Hello all,

I'm getting the following error when using the BaseHandler on python 3.5
module 'socket' has no attribute '_fileobject'

After checking the code source of socket I couls see this has been removed... :(

Thanks,

Alex.

**Comment by mhils** [comment]
Thanks. Looks like it's `socket.socket` now. 
We certainly need to have test coverage for that, contributions are welcome. :smiley:
