### ISSUE TITLE
dummy_cert is hardcoded to expire after 1 month

### ISSUE THREAD

**Issue by macmantrl** [mitmproxy/netlib#52]
dummy_cert is hardcoded to expire after 1 month.

Since server playback in mitmproxy relies on this, it means that you can only have a server running for a month before all of the dummy certificates start to expire. Only way to fix is by restarting the process.

**Comment by mhils** [comment]
Thanks for the report!

@cortesi: Is there a non-obvious reason why we chose just one month? Do we want to increase that or perform a check and then regenerate?

**Comment by macmantrl** [comment]
I would prefer a solution that allows mitmdump to run indefinitely (so re-generating after an expiration check would be nice)

**Comment by kiasaki** [comment]
+1

**Comment by programble** [comment]
+1

**Comment by alexcarruthers** [comment]
+1

**Comment by aGHz** [comment]
+1

**Comment by TimmyCarbone** [comment]
+1

**Comment by cortesi** [comment]
Well chaps, I guess we'd better do something about this. We have top men working on this. Top... men...

**Comment by kiasaki** [comment]
Great! Is it still worth making it check for expiry like @macmantrl proposed or 5 years is good enough? (I personally can live with 5 years expiry, the VM will probably be decommissioned way before)

**Comment by cortesi** [comment]
I think 5 years is probably good enough. I'd feel weird merging a pull request that has code that, by definition, will never be executed for at least 5 years. By then we'll all have flying cars and won't care about intercepting SSL anymore. ;)

**Comment by mhils** [comment]
We also want to keep the expiry date of our CA in a reasonable range, just because an extreme value could cause issues with some device/browser. If you have a hint how we could generate new CAs which are automatically trusted, I'm immediately implementing this. ;)

**Comment by alexcarruthers** [comment]
+1 for the indiana jones reference

**Comment by programble** [comment]
When can we expect a release of mitmproxy with this fix?

**Comment by cortesi** [comment]
At this point I think we're a week or two from release. The console app has gone through a significant refactoring, and I'd like that to bed in a bit before I spring it on the public. We also have a new logo that needs to be integrated throughout everything at the same time.
