### ISSUE TITLE
Syntax error in h2/h2.py

### ISSUE THREAD

**Issue by felixonmars** [mitmproxy/netlib#64]
I am getting the following error when trying to access h2/h2.py. The same error also appears on installation during the byte-compiling step.

```
$ python2 /usr/lib/python2.7/site-packages/netlib/h2/h2.py
  File "/usr/lib/python2.7/site-packages/netlib/h2/h2.py", line 83
    print "-> Setting changed: %s to %d (was %s)" %
                                                  ^
SyntaxError: invalid syntax
```

**Comment by Kriechi** [comment]
Yes - HTTP/2 support is still in its early alpha stage.
There will be PR later today/tomorrow which adds more support - and also fixes this issue.

Quickfix: just remove the line break to fix the print statement.
